### ISSUE TITLE
[Bug] Plugin not working

### ISSUE THREAD

**Issue by Lennord** [efekurbann/sync-commands#1]
Server info:

Minecraft Server Version:  Paper 1.16.5
Plugin Version:  V1.0.0:

Crash Bungeecord plugin:
```
[WARNING] Exception encountered when loading plugin: SyncCommands
xyz.efekurbann.synccommands.libs.jedis.exceptions.JedisConnectionException: Failed to create socket.
    at xyz.efekurbann.synccommands.libs.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:93)
    at xyz.efekurbann.synccommands.libs.jedis.Connection.connect(Connection.java:180)
    at xyz.efekurbann.synccommands.libs.jedis.Connection.initializeFromClientConfig(Connection.java:338)
    at xyz.efekurbann.synccommands.libs.jedis.Connection.<init>(Connection.java:53)
    at xyz.efekurbann.synccommands.libs.jedis.Jedis.<init>(Jedis.java:212)
    at xyz.efekurbann.synccommands.libs.jedis.JedisFactory.makeObject(JedisFactory.java:181)
    at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
    at xyz.efekurbann.synccommands.libs.jedis.util.Pool.getResource(Pool.java:34)
    at xyz.efekurbann.synccommands.libs.jedis.JedisPool.getResource(JedisPool.java:364)
    at xyz.efekurbann.synccommands.messaging.impl.redis.Redis.connect(Redis.java:36)
    at xyz.efekurbann.synccommands.SyncCommandsBungee.onEnable(SyncCommandsBungee.java:44)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.net.ConnectException: Connection refused: no further information
    at java.base/sun.nio.ch.Net.pollConnect(Native Method)
    at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
    at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at xyz.efekurbann.synccommands.libs.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:65)
    ... 16 more
```

Crash Paper-Spigot plugin:
```
[01:34:33 ERROR]: Error occurred while enabling SyncCommands v1.0 (Is it up to date?)
xyz.efekurbann.synccommands.libs.jedis.exceptions.JedisConnectionException: Failed to create socket.
        at xyz.efekurbann.synccommands.libs.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:93) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.Connection.connect(Connection.java:180) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.Connection.initializeFromClientConfig(Connection.java:338) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.Connection.<init>(Connection.java:53) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.Jedis.<init>(Jedis.java:212) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.JedisFactory.makeObject(JedisFactory.java:181) ~[?:?]
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.util.Pool.getResource(Pool.java:34) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.JedisPool.getResource(JedisPool.java:364) ~[?:?]
        at xyz.efekurbann.synccommands.messaging.impl.redis.Redis.connect(Redis.java:36) ~[?:?]
        at xyz.efekurbann.synccommands.SyncCommandsSpigot.onEnable(SyncCommandsSpigot.java:45) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:669) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
        at java.net.Socket.connect(Socket.java:645) ~[?:?]
        at xyz.efekurbann.synccommands.libs.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:65) ~[?:?]
        ... 22 more
[01:34:33 INFO]: [SyncCommands] Disabling SyncCommands v1.0
[01:34:33 ERROR]: Error occurred while disabling SyncCommands v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "xyz.efekurbann.synccommands.messaging.impl.redis.Redis$RedisPubSub.unsubscribe()" because "this.listener" is null
        at xyz.efekurbann.synccommands.messaging.impl.redis.Redis.close(Redis.java:69) ~[?:?]
        at xyz.efekurbann.synccommands.SyncCommandsSpigot.onDisable(SyncCommandsSpigot.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

Hello, I have these errors since the Bungeecord and the Paper-Spigot (1.16.5) but I tried to configure the 2 plugins correctly but it still does not work...
I hope you will be able to correct these errors.

**Comment by efekurbann** [comment]
Hey, thank you for reporting.

Seems like your redis configuration is wrong.
Are you sure the configuration is correct and plugin is able to connect your redis server? (like firewall issues or incorrect password)

**Comment by Lennord** [comment]
> Hey, thank you for reporting.
> 
> Seems like your redis configuration is wrong. Are you sure the configuration is correct and plugin is able to connect your redis server? (like firewall issues or incorrect password)

Hello, yes I have configured the 2 plugins well, I even reset the redis in the config but I still have no solutions.

**Comment by Lennord** [comment]
My config for the plugin Bungeecord:

```
serverName: "bungeecord" # anything you want

# this one also exists on the bungeecord because you can send commands to bungeecord!
connection: # connection to listen for new commands
  # currently there are 2 different types; socket and redis.
  # imo redis is better but its on you.
  #
  # you must use the same type as the other servers!
  type: redis
  host: "localhost"
  port: 25577
  password: "ipiagamesbungee987123987123"
  secure: true

servers:
  hub01:
    host: "localhost"
    port: 10000
    password: "ipiagameshub01987123987123"
    secure: true

no-permission: "&bIpiaGames &8&o¤ &cVous n'avez pas la permission d'utiliser cette commande !"
```

My config for the plugin Paper-Spigot:

```
serverName: "hub01"

connection:
  type: redis
  host: "localhost"
  port: 25577
  password: "ipiagamesbungee987123987123"
  secure: true

servers:
  hub01:
    host: "localhost"
    port: 10000
    password: "ipiagameshub01987123987123"
    secure: true

no-permission: "&cYou do not have enough permission to perform this command!"
```

**Comment by efekurbann** [comment]
In the servers section, you set server hub01's port as 10000 but in the connection section its set as 25577
i guess 10000 is your hub server's port and 25577 is your redis' port. or the opposite idk.
it confuses a bit but the port in servers section is redis port, not server's.
This may be the problem.

off-topic but if you are not going to use bsync command or send commands to bungeecord, you dont need bungee jar.
edit: secure setting is for ssl, if ssl is disabled for your redis server disable it as well

**Comment by efekurbann** [comment]
Here my config for redis, you can use this as a template.

```
serverName: "hub"

connection: # connection to listen for new commands
  type: redis
  host: "redis-13861.c293.eu-central-1-1.ec2.cloud.redislabs.com"
  port: 13861
  password: "mysupersecretredispass"
  secure: false

servers: # connections to send commands, not listen
  bungee:
    host: "redis-13861.c293.eu-central-1-1.ec2.cloud.redislabs.com"
    port: 13861
    password: "mysupersecretredispass"
    secure: false
  testserver:
    host: "redis-13861.c293.eu-central-1-1.ec2.cloud.redislabs.com"
    port: 13861
    password: "mysupersecretredispass"
    secure: false
```

**Comment by Lennord** [comment]
```
serverName: "hub01"

connection: # connection to listen for new commands
  type: redis
  host: "localhost"
  port: 10000
  password: "ipiagameshub1mdp987123"
  secure: false

servers: # connections to send commands, not listen
  bungee:
    host: "localhost"
    port: 25577
    password: "ipiagamesbungeemdp987123"
    secure: false

no-permission: "&bIpiaGames &8&o¤ &cVous n'avez pas la permission d'utiliser cette commande !"
```

Bungee port: 25577
Spigot server "Hub01": 10000

It still doesn't work.

**Comment by efekurbann** [comment]
its not server's port its redis's port

**Comment by Lennord** [comment]
> its not server's port its redis's port

Uh I don't understand, the redis port is the bungeecord port?

**Comment by efekurbann** [comment]
I mean, the redis server's port.
eg my redis port is 13861
Its completely different than spigot server's port.

I use redislab.com for testing purposes. https://prnt.sc/26lvkpd

**Comment by Lennord** [comment]
it works, thank you very much for your help...
Good continuation to evolve and improve this great plugin.

Have a good day.

**Comment by efekurbann** [comment]
Thank you, have a good day!
