### ISSUE TITLE
Issues when trying to sync commands for ServerGroup which contains executor's source server (where he is currently)

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [efekurbann/sync-commands#3]
For example, when you go to "Server1" and you try to execute "/sync ServerGroup1 say hello"...

...where inside of "ServerGroup" we have 2 servers:
- Server1
- Server2

this error will throw probably because you are trying to sync command from source to target server which are exactly the same (and this is not supported? from what i see it isn't)
```
[19:50:56 WARN]: [SyncCommands] Plugin SyncCommands v4.0.0 generated an exception while executing task 44
java.lang.NullPointerException: null
        at io.github.efekurbann.synccommands.messaging.impl.socket.SocketClient.sendCommand(SocketClient.java:21) ~[?:?]
        at io.github.efekurbann.synccommands.messaging.impl.socket.SocketImpl.lambda$publishCommand$0(SocketImpl.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[paper-1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[paper-1.12.2.jar:git-Paper-1620]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

although this DOES NOT happen when you are on Server1 and you try to do "/sync Server1 say hello" - instead it says that it can not find that server (probably because source and target servers are the same = Server1).

**Comment by efekurbann** [comment]
Hey, thanks for your report! 

Probably this will be fixed in the next release of SyncCommands. 
You will be able to synchronize commands to the same server in next version of SyncCommands.

Since I don't have much time right now, I can not give you a ETA, but as soon as possible.

**Comment by efekurbann** [comment]
Hey, the commit https://github.com/efekurbann/sync-commands/commit/e20138011f632eec1951c3f604346d47861335c5 should fix this and will be added to the next release.
