### ISSUE TITLE
Some things when target server is offline

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [efekurbann/sync-commands#4]
(bungeecord)

If you try to sync commands to some group of servers and if some server is offline, starting or restarting or shutting down / also if you try to only sync commands to only 1 server which is offline, starting or restarting or shutting down, it'll throw an error - is this error safe? by safe i mean, will that error cause plugin to stop working somehow? like to break
```
[19:43:22] [SyncCommands Pool Thread #2/ERROR]: java.net.ConnectException: Connection refused
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/sun.nio.ch.Net.connect0(Native Method)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/sun.nio.ch.Net.connect(Net.java:579)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/sun.nio.ch.Net.connect(Net.java:568)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.net.Socket.connect(Socket.java:633)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.net.Socket.connect(Socket.java:583)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.net.Socket.<init>(Socket.java:507)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.net.Socket.<init>(Socket.java:319)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at io.github.efekurbann.synccommands.messaging.impl.socket.SocketClient.sendCommand(SocketClient.java:21)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at io.github.efekurbann.synccommands.messaging.impl.socket.SocketImpl.lambda$publishCommand$0(SocketImpl.java:34)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:43:22] [SyncCommands Pool Thread #2/ERROR]:     at java.base/java.lang.Thread.run(Thread.java:833)
```

Will you think of caching commands which are executed to be sync if server is offline, then cache commands to be executed ONLY after that target server fully starts (and depending on the config from the target server, you can add option "execute-cached-commands-after-x-seconds-from-startup: 5" <-- and this will mean that after the target server has successfully started, ONLY IF there are cached commands from some other server who requested to send it, he has it cached and will try again when server is up (idk how efficient can we make this? it's not good to check infinite amount of times if server is online, and idk if the mentioned option above is then relevant because it probably won't be the case that server who's sending cached commands will get the timing when server JUST have started))

**Comment by efekurbann** [comment]
Hey, thanks for your report! 

Probably this will be fixed in the next release of SyncCommands. 
Since I don't have much time right now, I can not give you a ETA, but as soon as possible.

About caching the commands feature, I will take a look but I can't say something for sure.

And, it shouldn't break the plugin but some commands may not be synced correctly.

**Comment by efekurbann** [comment]
Hey, the commit https://github.com/efekurbann/sync-commands/commit/dcced76de21b8bcb8c63f4ad5cdc847aa2629a43 should fix this and will be added in the next release. Let me know if the problem still occurs.
